#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🤖 Validating commit message ...'
npx --no -- commitlint --edit "$1" || 
(
    echo '🙄 The commit message is improperly formatted. Please improve it.'
    false;
)
